_core:
  default_config_hash: YWbqKPHA3djohSgnBRKhK0NUjnO1dL1XmIo3yBw3oFo
minimum_single: 7
minimum_multiple: 6
disable_search_threshold: 7
minimum_width: 100
max_shown_results: null
use_relative_width: true
jquery_selector: 'select:not(.custom-chosen-select):not(.custom-select):not(#edit-classification):not(.selectize):visible'
search_contains: false
disable_search: false
allow_single_deselect: false
disabled_themes:
  seven: '0'
  bootstrap_barrio: '0'
  lib_unb_ca: '0'
  unb_lib_theme: '0'
chosen_include: 2
placeholder_text_multiple: '- Please choose 1 or more options -'
placeholder_text_single: '- Please choose an option -'
no_results_text: 'No results match'
